### ISSUE TITLE
Step 1 - Import DDB items error (ValidationException)

### ISSUE THREAD

**Issue by alexcasalboni** [aws-samples/aws-serverless-workshop-innovator-island#39]
When running the importData.js script, I got these errors:

```bash
$ node ./importData.js $AWS_REGION $DDB_TABLE
Trying batch:  0
Trying batch:  1
Error:  { ValidationException: The provided key element does not match the schema
    at Request.extractError (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'The provided key element does not match the schema',
  code: 'ValidationException',
  time: 2020-10-08T08:44:40.736Z,
  requestId: 'VDH25CO810GC2ROD3SAC0RI5Q7VV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 43.84522548134123 }
Error:  { ValidationException: The provided key element does not match the schema
    at Request.extractError (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/environment/theme-park-backend/1-app-deploy/local-app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'The provided key element does not match the schema',
  code: 'ValidationException',
  time: 2020-10-08T08:44:40.743Z,
  requestId: 'SP2IF6EG5RD8AOMBVVCQKQA3OBVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 6.5104707208255785 }
```

Only the first 16 items have been imported into my DDB tabl (up to `ID=ride-016`).

**Comment by alexcasalboni** [comment]
My bad, not an issue - I was in the wrong folder :)
